-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.clientes
(
    dni character varying(10) NOT NULL,
    nombre character varying(45) NOT NULL,
    apellido character varying(45) NOT NULL,
    codigo_postal integer NOT NULL,
    direccion character varying(45) NOT NULL,
    telefono_fijo character varying(45),
    telefono_celular character varying(45),
    correo character varying(100),
    PRIMARY KEY (dni)
);

CREATE TABLE IF NOT EXISTS public.ventas
(
    id_venta integer NOT NULL,
    fecha date NOT NULL,
    id_producto integer NOT NULL,
    dni character varying(10) NOT NULL,
    monto double precision NOT NULL,
    form_pago character varying(45) NOT NULL,
    PRIMARY KEY (id_venta)
);

CREATE TABLE IF NOT EXISTS public.productos
(
    id_producto integer NOT NULL,
    marca character varying(45) NOT NULL,
    talla character varying(45) NOT NULL,
    precio double precision NOT NULL,
    stock integer NOT NULL,
    PRIMARY KEY (id_producto)
);

CREATE TABLE IF NOT EXISTS public.proveedores
(
    id_proveedor integer NOT NULL,
    numero_puesto integer NOT NULL,
    nombre character varying(45) NOT NULL,
    apellido character varying(45) NOT NULL,
    codigo_postal integer NOT NULL,
    direccion character varying(45) NOT NULL,
    telefono_fijo character varying(45),
    telefono_celular character varying(45),
    correo character varying(100)
);

CREATE TABLE IF NOT EXISTS public.codigo_postales
(
    codigo_postal integer NOT NULL,
    localidad character varying(45) NOT NULL,
    PRIMARY KEY (codigo_postal),
    CONSTRAINT u_codigo_postal UNIQUE (codigo_postal)
);

ALTER TABLE IF EXISTS public.clientes
    ADD CONSTRAINT fk_cliente_codigo_postal FOREIGN KEY (codigo_postal)
    REFERENCES public.codigo_postales (codigo_postal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.ventas
    ADD CONSTRAINT id_producto FOREIGN KEY (id_producto)
    REFERENCES public.productos (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.ventas
    ADD CONSTRAINT dni FOREIGN KEY (dni)
    REFERENCES public.clientes (dni) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.proveedores
    ADD CONSTRAINT fk_proveedor_codigo_postal FOREIGN KEY (codigo_postal)
    REFERENCES public.codigo_postales (codigo_postal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;